### ISSUE TITLE
Only add once for --watch mode

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/add-asset-webpack-plugin#4]
When running `webpack --watch` with incremental compilations and with a static `string` type `source`, the module will still add it on every incremental build which is useless and spams the log unneccesarily. Suggesting to emit a `string` asset only once during `--watch`. Function/Promise sources should of course be emitted every build because their content may change.

**Comment by sindresorhus** [comment]
👍

**Comment by silverwind** [comment]
Not super familar with webpack API, but I think we need to find the correct hook and then call [compilation.emitAsset()](https://webpack.js.org/api/compilation-object/#emitasset) in it (as opposed to mutating `compilation.assets` which this module currently does).

**Comment by sibiraj-s** [comment]
You can do this.

```js

const existingAsset = compilation.getAsset('assetName')

if(!existingAsset) {
  compilation.emitAsset('assetName',  source)
}
```

**Comment by silverwind** [comment]
Thanks. Maybe I'll incorporate that in https://github.com/sindresorhus/add-asset-webpack-plugin/pull/6 if input is a string (If it's a function, we need to emit every time).
